"use client";

interface ComplianceSummaryProps {
  companyName: string | null;
  platform: string | null;
  riskTags: string[];
  summary: string | null;
  isLoading: boolean;
}

export default function ComplianceSummaryCard({
  companyName,
  platform,
  riskTags,
  summary,
  isLoading,
}: ComplianceSummaryProps) {
  return (
    <div className="rounded-xl border border-border bg-card p-6 flex flex-col gap-4 col-span-1 md:col-span-2 lg:col-span-3">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <h2 className="text-sm font-semibold uppercase tracking-widest text-muted-foreground">
          AI Compliance Report
        </h2>
        {companyName && !isLoading && (
          <div className="flex items-center gap-2">
            <span className="text-xs text-muted-foreground">{platform}</span>
            <span className="text-xs font-semibold text-foreground">
              {companyName}
            </span>
          </div>
        )}
      </div>

      {/* Risk Tags */}
      {!isLoading && riskTags.length > 0 && (
        <div className="flex flex-wrap gap-2">
          {riskTags.map((tag) => (
            <span
              key={tag}
              className="text-xs px-2.5 py-1 rounded-full border border-amber-500/30 bg-amber-500/10 text-amber-400 font-medium"
            >
              ⚑ {tag}
            </span>
          ))}
        </div>
      )}

      {/* Summary Text */}
      <div className="rounded-lg bg-muted/30 border border-border p-4 min-h-[80px]">
        {isLoading ? (
          <div className="flex flex-col gap-2 animate-pulse">
            <div className="h-3 bg-gray-700 rounded w-full" />
            <div className="h-3 bg-gray-700 rounded w-5/6" />
            <div className="h-3 bg-gray-700 rounded w-4/6" />
          </div>
        ) : summary ? (
          <p className="text-sm text-foreground leading-relaxed">{summary}</p>
        ) : (
          <p className="text-sm text-muted-foreground italic">
            Run an audit to see the AI-generated compliance report.
          </p>
        )}
      </div>

      {!isLoading && summary && (
        <p className="text-xs text-muted-foreground">
          Generated by Gemini 2.5 Flash · K-Trust Compliance Engine v1.0
        </p>
      )}
    </div>
  );
}